### ISSUE TITLE
no -db from mysql notification follows

### ISSUE THREAD

**Issue by aidaka** [cascax/sql2gorm#3]
![图片](https://user-images.githubusercontent.com/43767933/183620796-cd218746-8d47-46fd-a19d-00bcbdc6e958.png)

--------------------------------------------
\sql2gorm@v0.0.1>sql2gorm -db-dsn=root:123456@/gitea -db-table=task
flag provided but not defined: -db-dsn
Usage of sql2gorm:
  -col-prefix string
        column name prefix
  -f string
        input file
  -json
        generate json tag
  -no-null
        do not use Null type
  -null-style string
        null type: sql.NullXXX(use 'sql') or *xxx(use 'ptr')
  -o string
        output file
  -pkg string
        package name, default: model
  -sql string
        input SQL
  -table-prefix string
        table name prefix

**Comment by cascax** [comment]
I just added a tag v0.0.2. Please use `go install github.com/cascax/sql2gorm@v0.0.2`
